Update upgrading.md
1. rladmin status all - is a wrong command: 
rladmin status all
ERROR: invalid token 'all'

Should be:  `rladmin status extra all`

need to add what is the indicator for out of date database - OLD REDIS VERSION